### ISSUE TITLE
Lovely!

### ISSUE THREAD

**Issue by pestaa** [webburza/sylius-google-ecommerce-bundle#2]
Great work, thanks.

**Comment by dkarlovi** [comment]
@pestaa thanks! Have you managed to get it running? Do you have any suggestions for the README? For example, something to make more clear, etc.

**Comment by pestaa** [comment]
@dkarlovi Yes! Wiring it up was easy. (We had one problem only: the key parameter is mandatory, so we tricked the bundle to render tags only when a valid key is provided.)

Now waiting for launch date and numbers to show up. :)
